spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db1
    username: root
    password: LuhaismyMan12
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
  jpa:
    database: h2
  h2:
    console:
      enabled: true